manual/winaero-tweaker.install/README.md, manual/winaero-tweaker.install/tools/chocolateyinstall.ps1, manual/winaero-tweaker.install/winaero-tweaker.install.nuspec, manual/winaero-tweaker.portable/README.md, manual/winaero-tweaker.portable/tools/chocolateyinstall.ps1, manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec, manual/winaero-tweaker/winaero-tweaker.nuspec
Updated the Winaero Tweaker package to the 0.18.0 version.
=> (gh-197) Updated Winaero Tweaker package to 0.18.0

automatic/sqlite.shell/update.ps1
Enhanced logging to record details for each step in the pre-update phase.
=> (gh-274) Enhanced logging

automatic/flashpoint-core/update.ps1, automatic/flashpoint-infinity/update.ps1
Updates were failing as the regex was not matching a version in the URL
when the au_GetLatest script was called. called.  With no version number
being extracted the package update is failing.
Updated version regex to correctly match versions and included handling
to append a '.0' to the extracted version if only an integral value was
returned.
=> (gh-304) Update version extraction

automatic/flashpoint-core/update.ps1, automatic/flashpoint-infinity/update.ps1
Update to regular expression matching checksums in the install scripts.
=> (gh-304) Update checksum matching

manual/winaero-tweaker.install/README.md, manual/winaero-tweaker.install/tools/chocolateyinstall.ps1, manual/winaero-tweaker.install/winaero-tweaker.install.nuspec, manual/winaero-tweaker.portable/README.md, manual/winaero-tweaker.portable/tools/chocolateyinstall.ps1, manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec, manual/winaero-tweaker/README.md, manual/winaero-tweaker/winaero-tweaker.nuspec
Updated the Winaero Tweaker package to 1.20.1.0 and removed the version
truncation in the package argument generation.
=> (gh-349) Updated Winaero Tweaker package to 1.20.1.0

manual/winaero-tweaker.install/README.md, manual/winaero-tweaker.install/winaero-tweaker.install.nuspec, manual/winaero-tweaker.portable/README.md, manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec, manual/winaero-tweaker/README.md, manual/winaero-tweaker/winaero-tweaker.nuspec
Update Winaero Tweaker package version to 1.31.0.0.
=> (gh-355) Update Winaero Tweaker Package Version 1.31

manual/winaero-tweaker.install/README.md, manual/winaero-tweaker.install/tools/chocolateyinstall.ps1, manual/winaero-tweaker.install/winaero-tweaker.install.nuspec, manual/winaero-tweaker.portable/README.md, manual/winaero-tweaker.portable/tools/chocolateyinstall.ps1, manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec, manual/winaero-tweaker/README.md, manual/winaero-tweaker/winaero-tweaker.nuspec
Update Winaero Tweaker package version to 1.40.0.0.
=> (gh-405) Update Winaero Tweaker Package Version 1.40

automatic/logrotate/tools/chocolateyBeforeModify.ps1, automatic/logrotate/tools/chocolateyInstall.ps1, automatic/logrotate/tools/helpers.ps1, automatic/logrotate/update.ps1
Modified the regular expression used when matching in the update script and modified the installation to ensure that package upgrades were possible.
=> (gh-426) Corrected update script and refactored install

automatic/beekeeper-studio/update.ps1
Updated latest version retrieval handling inline with GitHub page restructure.  Rather than scraping directly from the assets page a URL redirection needs to be handled to determine the latest tag and extract the relevant download URLs.
=> (gh-447) Update package version retrieval

automatic/sqljdbc/tools/chocolateyUninstall.ps1
Update script was using private env variable $chocolateyPackageFolder.
Updated to use Get-ChocolateyPath instead.
=> (gh-461) Modified package update to avoid private env use

automatic/kindlepreviewer/tools/chocolateyInstall.ps1
Updated not working link and package itself
=> (gh-411) Update to current version

automatic/vscode-arduino/update.ps1
The token being used in search/replace for the uninstaller in package updates was incorrect - this was causing updates to fail.  Modified the matching token to correct this and updated to use globally declared  regular expressions.
=> (gh-539) Corrected uninstall token

manual/office365proplus/Office365ProPlus.nuspec
The package title contained a spelling error - updated from Proofessional to Professional.
=> (gh-528) Corrected Package Title

automatic/mousewithoutborders/README.md, automatic/mousewithoutborders/update.ps1
The update script was not functioning as expected.  Modified the script to correctly match version numbers and urls and amended package README.md to reference the Chocolatey community site.
=> (gh-558) Modified update script

automatic/simple-sticky-notes/simple-sticky-notes.nuspec
License and validation information were not included in the package - the legal folder was not included in the package build.  Updated the .nuspec definition to ensure that the legal directory and contents was included.
=> (gh-582) Included license and validation information in package

automatic/mc/README.md, automatic/mc/legal/VERIFICATION.txt, automatic/mc/mc.nuspec, automatic/mc/tools/chocolateyInstall.ps1, automatic/mc/update.ps1
Update package location to Github and ensure automatic updates are functioning as expected.  Package also modified to reflect the availability of a 64-bit build.
=> (gh-586) Update package location to Github and add 64-bit

automatic/rsync/README.md, automatic/rsync/legal/VERIFICATION.txt, automatic/rsync/rsync.nuspec, automatic/rsync/update.ps1
Package was no longer updating as the URL for downloads had been updated.  Corrected this and updated documentation links and regex handling.
=> (GH-588) Modified to use updated URL for binaries.

automatic/sqljdbc/README.md, automatic/sqljdbc/sqljdbc.nuspec, automatic/sqljdbc/tools/chocolateyInstall.ps1, automatic/sqljdbc/update.ps1
The pattern for the download URL had changed to include an additional language-specific segment.  Added support for this and made some minor code an documentarian updates for additional clarity.
=> (gh-576) Revised download handling and updated documentation

automatic/remote-desktop-client/update.ps1
File download locations were previously provided by an API call.  These API calls have been removed with the redirect URL now  directly referencing the download.
Removed the API handling and updated to handle the direct URI.
=> (gh-622) Modified latest retrieval to use direct download

automatic/vscode-arduino/README.md, automatic/vscode-arduino/legal/VERIFICATION.txt, automatic/vscode-arduino/tools/chocolateyInstall.ps1, automatic/vscode-arduino/tools/chocolateyUninstall.ps1, automatic/vscode-arduino/tools/chocolateyuninstall.ps1, automatic/vscode-arduino/update.ps1, automatic/vscode-arduino/vscode-arduino.nuspec
The package from Microsoft had been deprecated.  Updated package to relfect the new package details post migration to the community-supported fork.
=> (gh-619) Modified package details
