dgalbraith/chocolatey-packages

- automatic/vscode-chrome-debug/legal/VERIFICATION.txt
- automatic/vscode-chrome-debug/vscode-chrome-debug.nuspec
- automatic/vscode-edge-debug/legal/VERIFICATION.txt
- automatic/vscode-edge-debug/vscode-edge-debug.nuspec
- automatic/vscode-firefox-debug/legal/VERIFICATION.txt
- automatic/vscode-firefox-debug/vscode-firefox-debug.nuspec
- automatic/vscode-intellicode/legal/VERIFICATION.txt
- automatic/vscode-intellicode/vscode-intellicode.nuspec
- automatic/vscode-java-debug/legal/VERIFICATION.txt
- automatic/vscode-java-debug/vscode-java-debug.nuspec
- automatic/vscode-java-dependency/legal/VERIFICATION.txt
- automatic/vscode-java-dependency/vscode-java-dependency.nuspec
- automatic/vscode-java-test/legal/VERIFICATION.txt
- automatic/vscode-java-test/vscode-java-test.nuspec
- automatic/vscode-java/legal/VERIFICATION.txt
- automatic/vscode-java/vscode-java.nuspec
- automatic/vscode-kubernetes-tools/legal/VERIFICATION.txt
- automatic/vscode-kubernetes-tools/vscode-kubernetes-tools.nuspec
- automatic/vscode-maven/legal/VERIFICATION.txt
- automatic/vscode-maven/vscode-maven.nuspec
- automatic/vscode-prettier/legal/VERIFICATION.txt
- automatic/vscode-prettier/vscode-prettier.nuspec
- automatic/vscode-python/legal/VERIFICATION.txt
- automatic/vscode-todo-tree/legal/VERIFICATION.txt
Updated license references to use those in the extension distribution
rather than the source code repository.  This was to address the
possibility that the licensing for the binary distribution and the
source code may diverge over time.  Given it is the binary which is
being redistributed the license needed to be aligned.
> Updated license references - fixes gh-1

- automatic/vscode-prettier/README.md
- automatic/vscode-prettier/vscode-prettier.nuspec
In-line HTML is not rendered in package descriptions on chocolatey.org.
The package description was updated to remove the in-line HTML.
Fixes GH-5.
> GH-5 Removed in-line html from package description

- automatic/vscode-go/README.md
The icon used in the README.md for vscode-go package was incorrect. It
was using an incorrect reference and needed to be updated to reflect the
proper icon.
> (gh-27) Corrected VSCode Go extension icon

- automatic/vscode-beautify/vscode-beautify.nuspec
The release notes reference in the package definition was incorrect.
Updated to reference the correct location.
> (gh-33) Updated relase notes reference

- automatic/vscode-java-debug/legal/VERIFICATION.txt
- automatic/vscode-java-debug/vscode-java-debug.nuspec
The description and verification URLs were incorrect.  Updated the
screenshot CDN URL to remove eroneous package extensions and
amended the direct package download verification URL to add the
full package name.
> (gh-36) Updated description and verification URLs.

- automatic/neck-diagrams/README.md
- automatic/neck-diagrams/neck-diagrams.nuspec
Updated package title to remove the version from the title - the version
is supplied in the package tag.
Updated the Copyright notice to reflect updates in the year 2020.
Updated package source URL.
Updated package icon URL.
Updated release notes URL.
> (gh-58) Updated package title, copyright notice and other documentation

- automatic/neck-diagrams/update.ps1
Updated au_SearchReplace to remove the "(\s*version\s*=\s*)('.*')"
update to ensure successful token replacement in chocolateyInstall.ps1.
Token replacement was failing as there is no match for the string version=
in the target file.
> (gh-59) removed invalid matching regex

- manual/winaero-tweaker.install/winaero-tweaker.install.nuspec
- manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec
- manual/winaero-tweaker/winaero-tweaker.nuspec
Package titles for Winaero Tweaker did not differentiate the install and
portable versions from  the meta package and were updated to include
Install and Portable in the title.
Copyright notices were updated to include the text Copyright.
> (gh-57) Updated package titles and copyright notices

- automatic/keys/README.md
- automatic/keys/keys.nuspec
The package title was co-indident with the package name and did not
convey any information as to the purpose of the package.  The title was
updated to provide additional detail.
> (gh-72) Update package title

- automatic/keys/update.ps1
The regex to match the installer on update was not corrrect.  The regex
in place would not match msi which would cause an automated update to
fail.  Corrected the regex so it would correctly pick up the Keys msi.
> (gh-82) Updated regex matching installer in update script

- automatic/kyma-cli/update.ps1
The URL used to match against when determining the version is empty so
the version matching will return nothing.  To ensure a version is
returned when the update script is run the version match needs to be
performed against a populated URL.
Updated the URL used for the match to $url64 to achieve this.
> (gh-83) Updated URL matched for version in update script

- automatic/tunein-radio/README.md
- automatic/tunein-radio/tunein-radio.nuspec
The package definition was not correct due to the non-locateable icon.
The icon was not locatable due to an error in the URL.  To correct the
package definition the URL was corrected so that the icon could be
accessed at the URL.
The documentation was also updated to remove a linebreak such that the
display was clean.
> (gh-93) Corrected icon URL in package definition

- automatic/tldr/tldr.nuspec
The definition of the tldr++ client dependency was incorrect.  With an
exclusive minimum version matching the desired dependency version it
was not being located successfully.
Given the behaviour of the Chocolatey internal Nuspec version for an
unspecified dependency version is to locate the highest available
version there is in fact no need for an explicit version so this was
removed.
> (gh-102) Removed version specification from dependency

- automatic/vscode-prettier/README.md
- automatic/vscode-prettier/vscode-prettier.nuspec
The default branch name was changed from master --> main on the source repository.  Documentation references were updated accordingly.
> (gh-107) Updated documentation references to reflect default branch name change

- automatic/vscode-go/README.md
- automatic/vscode-go/legal/LICENSE.txt
- automatic/vscode-go/legal/VERIFICATION.txt
- automatic/vscode-go/tools/chocolateyinstall.ps1
- automatic/vscode-go/tools/chocolateyuninstall.ps1
- automatic/vscode-go/update.ps1
- automatic/vscode-go/vscode-go.nuspec
The vscode-go extension was migrated to the official golang project.  The
extension naming and documentation needed to be updated to reflect the
migration.
> (gh-109) Updated vscode-go extension to reflect migration

- automatic/vscode-live-share-audio/update.ps1
The extension definitions in the automatic update script for the
vscode-live-share extension were not correct.  They were referencing
the live share extension rather than the live share audio extension.
> (gh-123) Modify extension definitions in update script

- deprecated/vscode-live-share/README.md
- deprecated/vscode-live-share/tools/chocolateyinstall.ps1
- deprecated/vscode-live-share/vscode-live-share.nuspec
Made updates inline with the Chocolatey guidelines to fully deprecate
the package.  The package was deprecated as there was another
realisation of the package already available.
> (gh-121) Deprecated  inline with Chocolatey guidelines

- automatic/vscode-pull-request-github/README.md
- automatic/vscode-pull-request-github/legal/VERIFICATION.txt
- automatic/vscode-pull-request-github/tools/chocolateyinstall.ps1
- automatic/vscode-pull-request-github/update.ps1
- automatic/vscode-pull-request-github/vscode-pull-request-github.nuspec
The package updater for the GitHub Pull Requests and Issues VSCode
extension was pulling in a bad version which did not exist.  This was
due to an error in the name of the extension used in the update script
with a version being pulled in for a completely unrelated extension.
Corrected the extension used in the updater and ensured that version
references were aligned accordingly.
> (gh-138) Corrected GitHub Pull Requests extension pack updater

- scripts/vs-marketplace/functions/Get-VSMarketplaceExtensionDetails.ps1
Resource files were not being successfully located.  Included the
$PSScriptRoot in the resource prefix to support location at runtime.
> (gh-158) Use $PSScriptRoot for resource scoping

- scripts/vs-marketplace/functions/Get-VSMarketplaceExtensionDetails.ps1
The function Get-VSMarketplaceCopyrightMappings was declared twice.
Removed the second declaration.
> (gh-158) Removed additional function declaration

- automatic/vscode-go-test-adapter/update.ps1
- automatic/vscode-go-test-adapter/vscode-go-test-adapter.nuspec
- automatic/vscode-test-explorer/update.ps1
- automatic/vscode-test-explorer/vscode-test-explorer.nuspec
Email addresses are not valid for inclusion in a copyright element of a
Chocolatey package definition.  Modified package definitions to remove
email addresses and update scripts to ensure that they are not included
going forward.
> (gh-162) Modified update script to remove email address

- automatic/pictus.install/pictus.install.nuspec
- automatic/pictus.portable/pictus.portable.nuspec
- automatic/pictus/pictus.nuspec
Updated package descriptions to address  invalid markdown headings.
Headers in the package descriptions were missing a space between the
format descriptor and heading text.
> (gh-178) Updated description markdown headings

- automatic/lsasecretsview/README.md
- automatic/lsasecretsview/lsasecretsview.nuspec
The LSASecretsView package is generating a number of positives on virus
scanning.  The documentation was updated to provide a treatment of this.
> (gh-185) Update LSASecretsView documentation

- automatic/dotcover-cli/tools/chocolateyInstall.ps1
The package install script is failing verification due to a syntax error
caused by a missing `'` on a string.  The string needs to be
updated to include the opening `'` to ensure the syntax is valid.
> (gh-195) Update package install script

- automatic/dotcover-cli/tools/chocolateyInstall.ps1
- automatic/dotcover-cli/update.ps1
Package updates were incorrectly modifying the install script due to
excessive matching on the regular expression.  The expression needed to
be updated to match on word boundaries to support the match within the
string of the package version only to preserve the correct syntax in the
update script.
> (gh-201) Modified update script to match on boundaries

- automatic/cloc/update.ps1
The AU automatic update for the CLOC package was failing due to a
mismatch in the regular expression extracting the url.  An empty URL was
being extracted which ensured that the version number was not able to be
extracted.  The lack of the version number was breaking the update.
Corrected the URL extraction to provide a valid URL and ensure the
availability of the version number.
> (gh-209) Fix CLOC Automatic Update

- automatic/prime95/README.md
- automatic/prime95/prime95.nuspec
- automatic/prime95/update.ps1
The Prime95 package was failing validation due to an invalid URL in the
Bugtracker element. The element is currently an email address which is
not supported by the package validator.  Removed the Bugtracker element
as there is no alternative to email available - Prime95 does not have a
public bug tracker.
There was also an issue with the automatic update picking up unintended
additional version strings.  Reverted these version strings to the
correctvlegacy version and modified the update script to ensure that
they would not be picke up in future.
> (gh-213) Correct Prime95 Bugtracker Url

- manual/mssqlserver-compact4.0/README.md
- manual/mssqlserver-compact4.0/legal/VERIFICATION.txt
- manual/mssqlserver-compact4.0/mssqlserver-compact4.0.nuspec
- manual/mssqlserver-compact4.0/tools/chocolateyInstall.ps1
Minor updates to the SQL Server Compact package:
* modified the grammar used for the language example, removed the CI
build status link given the package is manual
* updated formatting in the verification instructions
* amended the install script to use a struct versus class for compatibility
with earlier Powershell versions
> (gh-152) SQL Server Compact Package Updates

- automatic/beekeeper-studio.install/README.md
- automatic/beekeeper-studio.install/update.ps1
- automatic/beekeeper-studio.portable/README.md
- automatic/beekeeper-studio.portable/update.ps1
- automatic/beekeeper-studio/README.md
- automatic/beekeeper-studio/update.ps1
- automatic/kui/kui.nuspec
- automatic/kui/update.ps1
- automatic/mongodb-shell/README.md
- automatic/mongodb-shell/update.ps1
- automatic/sd-cli/README.md
- automatic/sd-cli/update.ps1
- automatic/tldr-plusplus/README.md
- automatic/tldr-plusplus/update.ps1
- automatic/watchman/README.md
- automatic/watchman/tools/chocolateyinstall.ps1
- automatic/watchman/update.ps1
A number of packages were reporting errors on checking for updates - the
correct versions were not being resolved on update checks.  There were
2 separate categories here - handling of updates for packages where no
windows version was provided and errors in the matching of the URLs on
the download page for version determination.
The pacakges sd-cli, tldr-plusplus amd watchman were in category 1 while
beekeeper-studio, kui and mondodb-shell were in category 2.
Updated handling or matching to deal with each of these scenarios
cleanly.
> (gh-248) Ensure correct version resolution on update

- automatic/flashpoint-core/README.md
- automatic/flashpoint-core/flashpoint-core.nuspec
- automatic/flashpoint-core/tools/chocolateyBeforeModify.ps1
- automatic/flashpoint-core/tools/chocolateyInstall.ps1
- automatic/flashpoint-core/update.ps1
- automatic/flashpoint-infinity/README.md
- automatic/flashpoint-infinity/flashpoint-infinity.nuspec
- automatic/flashpoint-infinity/tools/chocolateyBeforeModify.ps1
- automatic/flashpoint-infinity/tools/chocolateyInstall.ps1
- automatic/flashpoint-infinity/tools/chocolateyUninstall.ps1
- automatic/flashpoint-infinity/update.ps1
- automatic/flashpoint-launcher/README.md
- automatic/flashpoint-launcher/flashpoint-launcher.nuspec
- automatic/flashpoint-launcher/tools/chocolateyBeforeModify.ps1
- automatic/flashpoint-launcher/tools/chocolateyUninstall.ps1
- automatic/flashpoint-launcher/tools/chocolateyinstall.ps1
- automatic/flashpoint-launcher/update.ps1
Various updates to the Flashpoint packages to ensure portability across
all architectures and that the automatic updates.  The packages were failing
to install on architectures other than Windows 10 due to excess path
lengths - archive extraction was failing due to the overall path length
exceeding 260 characters.
> (gh-250) Flashpoint package updates

- automatic/vscode-jupyter/update.ps1
Updated the regular expression matching on the version of VSCode
required by the extension.  The requirement had been set to an Insiders
edition which was no longer being matched by the regular expression
which considered digits only.
An update to the regular expression to accommodate this was needed.
> (gh-253) VSCode Jupyter required version matching update

- automatic/flashpoint-infinity/update.ps1
The automated updater is failing on extracting the archive name from the
URL. The failure is occurring due to an order of precedence in the
expression with a parameter binding before evaluation of the LHS string
evaluation.
Update the string evaluation with parentheses to ensure the expected
order of evaluation.
> (gh-254) Flashpoint Infinity update error

- automatic/beekeeper-studio.portable/tools/chocolateyuninstall.ps1
- automatic/beekeeper-studio.portable/update.ps1
Uninstall was not being handled correctly as the versions for the portable
package were not included in the update scripts - the handling in the
update script had been removed to the uninstall pointed to an older
package version.
> (gh-263) Correct uninstall handling for beekeeper studio portable package

- manual/go-fonts/README.md
- manual/go-fonts/legal/VERIFICATION.txt
- manual/go-fonts/tools/chocolateyInstall.ps1
Update the go-fonts package version to 2.008.  Package version was
updated and additional smallcaps font faces included.
> (gh-268) Update go-fonts package version to 2.008.

- automatic/beekeeper-studio/update.ps1
Updated the regular expression used on version matching by escaping the
'.' character to match the literal rather than additional characters.
> (gh-270) Update regular expression for version match

- automatic/ssrs-2019/README.md
- automatic/ssrs-2019/ssrs-2019.nuspec
- automatic/ssrs-2019/tools/chocolateybeforemodify.ps1
- automatic/ssrs-2019/tools/chocolateyinstall.ps1
- automatic/ssrs-2019/update.ps1
The edition parameter on the install was being defaulted in all instances
which was causing an installation error if a PID was specified.  The
edition and PID parameters are mutually exclusive so the edition should
not be defaulted when a PID is supplied.
> (gh-272) Default edition only if PID not supplied

- automatic/sqlite.shell/sqlite.shell.nuspec
- automatic/sqlite.shell/update.ps1
An additional 'l' in the package source URL was responsible for making
the URL an invalid one.  Removed the additional 'l' in sqllite to
correct this.
The archive was not being extracted as expected due to an error in the
arguments passed to Expand-Archive.  The destination argument was not
fully specified as it was being passed as '-Destination' rather than
'-DestinationPath'.
> (gh-274) SQLite Shell package update issues

- automatic/sqlite.shell/update.ps1
Automated builds were failing due to differences with  POSH 5 which the
update script was being run against.  Full paths were not being
retrieved which was leading to the build failures.
Given the cause of the build failures were now known additional logging
was also removed.
> (gh-274) Updated for POSH 5 compatability

- automatic/virtualclonedrive/virtualclonedrive.nuspec
Update to the package title for Virtual CloneDrive to ensure correct
capitalization.  The second letter of clone was incorrectly capitalized
so read CLone rather than clone.
> (gh-290) Amend package title

- automatic/ssrs-2019/ssrs-2019.nuspec
- automatic/ssrs-2019/tools/chocolateybeforemodify.ps1
Manually update the ssrs-2019 package to reflect the new product version
15.0.1102.896 which relates to the file version 15.0.7765.17516 formerly
used to sequence releases.
Updated the chocolateyBeforeModify.ps1 to include an ErrorActionPreference
directive.
> (gh-288) Bridge new product to file versioning

- automatic/cloc/update.ps1
The regular expression extracting the version needed to be updated to
correctly match the version in the download url.  There was an issue with
the regex which was not correctly matching so no version was being
extracted for use in the automatic update.
> (gh-297) Modify version regex for correct  capture

- automatic/fluidsynth/fluidsynth.nuspec
Update to the package title for Virtual FluidSynth to correct the use
of `SoundFront` to `SoundFont`.
> (gh-302) Amend package title

- automatic/angband/tools/chocolateyUninstall.ps1
- automatic/angband/update.ps1
The chocolateyUninstall.ps1 file was not  included in the automatic
updates.  This resulted in a stale version being left in the uninstall
script which referred to a prior zip file on the uninstall.
The automatic update script was modified to include the uninstall
script and the version synchronized with the current package version.
> (gh-305) Include uninstall script in automatic updates

- automatic/mongodb-shell/README.md
- automatic/mongodb-shell/legal/VERIFICATION.txt
- automatic/mongodb-shell/mongodb-shell.nuspec
- automatic/mongodb-shell/tools/chocolateyinstall.ps1
- automatic/mongodb-shell/update.ps1
Updates were failing as the filename regex is no longer matching - with the 0.13.0 version the structure of the
filename was changed.
File naming scheme has moved from mongosh-0.12.1-win32.zip to mongosh-0.13.0-win32-x64.zip.
> (gh-309) MongoDB Shell automatic package updates failing

- automatic/gephi/tools/chocolateyInstall.ps1
The 'AddToQuickLaunch' option was not being applied if selected on
package install.  The option was not being selected due to an extra
character in the handling - AddToQuickLauncch as opposed to
AddToQuickLaunch.
> (gh-319) Update AddToQuickLaunch option

- automatic/sqljdbc/update.ps1
Removed module import.  Additional module import was causing a run
failure as it was not running in the context of the normal au calling
wrapper which was providing the function context for the
Get-PackageParameters call.
> (gh-181) Remove module import

- automatic/sigcheck/README.md
- automatic/sigcheck/update.ps1
The version updates were incorrectly appending a new version with the
previous one whihc broke the regular expression matching for version
replacement.  The version in the README.md needed to be reset to a valid
version and the regular expression and update matching modified.
> (gh-328) Update version replacement

- automatic/mongodb-cli.install/update.ps1
- automatic/mongodb-cli.portable/update.ps1
Package updates were failing due to the absence of FileName64 in the
latest environment when search/replace was taking place.  This was
missing due to $Latest being mis-spelled as $Lagest in the initial
assignment.
> (gh-318) Access FileName64 during package updates

- automatic/mongodb-cli.portable/update.ps1
An incorrect regular expression was being used when matching the
filenames in VERIFICATION.txt.  The expression was matching on .msi
files rather than the correct .zip.   The regular expression being used
was changed to correct this.
> (gh-318) Match portable files in verification updates

- automatic/mongodb-cli.install/tools/chocolateyinstall.ps1
- automatic/mongodb-cli.install/update.ps1
- automatic/mongodb-cli.portable/tools/chocolateyinstall.ps1
- automatic/mongodb-cli.portable/update.ps1
Install scripts (chocolateyInstall.ps1) were not being picked up by the
package updates.  Modified the automatic update scripts to ensure that
the install scripts were updated with a new version of the file on
version change.
> (gh-318) Modify install scripts on update

- automatic/nushell.portable/legal/VERIFICATION.txt
- automatic/nushell.portable/nushell.portable.nuspec
- automatic/nushell.portable/tools/chocolateyInstall.ps1
Package updates were failing as the regex were not matching the file
extension - .msi was being used instead of .zip.
> (gh-341) Update file  extensions

- automatic/mongodb-cli.portable/legal/VERIFICATION.txt
Package updates were failing as the regex was not matching the file
extension - .msi was being used instead of .zip.
> (gh-342) Update file  extensions

- manual/mssqlserver-compact4.0/mssqlserver-compact4.0.nuspec
- manual/mssqlserver-compact4.0/tools/chocolateyInstall.ps1
I recently tried to install this package from the community repository. While the install of the underlying software succeeded, the tail end of the script bombed out with the following error:
```
ERROR: Cannot bind argument to parameter 'Path' because it is null.
```
The offending block was [here](https://github.com/dgalbraith/chocolatey-packages/blob/ffda32f8009fc24e6b7e73ef8bd3166d5741a8f5/manual/mssqlserver-compact4.0/tools/chocolateyInstall.ps1#L83):
```ps1
foreach ($file in $files) {
Remove-Item $file.ignore -Type file -Force -ErrorAction Ignore | Out-Null
}
```
There were a few different issues with this:
- I assume the intention here was to **create** `.ignore` files for the self-extracting archive binaries that are redistributed with the package, in order to prevent shims from …
> [mssqlserver compact4.0] Fix install script failure

- automatic/openvpn/README.md
- automatic/openvpn/openvpn.nuspec
Package uploads were failing due to the length of the package
description.  As the description was greater than 4000 characters the
underlying nuget field length was being exceeded and the package upload
failing.
> (gh-352) Update description to ensure < 4000 characters

- automatic/mongodb-cli.portable/legal/VERIFICATION.txt
- automatic/mongodb-cli.portable/tools/chocolateyinstall.ps1
- automatic/mongodb-cli.portable/update.ps1
The package update script was not correctly handling updates due to the
portable package filename being mapped from the intended .zip file to a
.msi file.
This was occuring on file retrieval in AU due to a fallback
to a .msi file.  With no FileType being specified the downloaded file was
being saved as a .msi rather than a .zip and this was propagated
forward which resulted in an incorrect filename being used.
An explicit filetype needed to be specified in the case of the zip file.
> (gh-371) Correct package update script

- automatic/nushell.install/tools/chocolateyInstall.ps1
- automatic/nushell.install/tools/chocolateyUninstall.ps1
Shims for the package were being installed with an additional .exe
appended.  The names used for shim generation needed updating to remove
the .exe as this is added automatically in Install-BinFile - if a file
already has the .exe extension it would be added again resulting in a
shim ending with .exe.exe.
> (gh-370) Correct names used for shim generation

- automatic/nushell.portable/legal/VERIFICATION.txt
- automatic/nushell.portable/tools/chocolateyInstall.ps1
- automatic/nushell.portable/update.ps1
Corrected automatic pacakge updates by resetting the filenames to have
the correct extensions (.zip) and modified the update script to specify
an explicit file type (.zip) to avoid defaulting to .msi.
> (gh-377) Corrected automatic package updates

- automatic/mongodb-cli.install/update.ps1
- automatic/mongodb-cli.portable/update.ps1
The URL validation is causing an error on package build with the
package URLs being incorrectly identified as invalid.  The URLs are
actually correct so supressing the URL check for now to avoid the
issue.
> (gh-380) Supress URL validation on package build

- automatic/watchman/tools/chocolateyinstall.ps1
- automatic/watchman/update.ps1
Package installation was failing due to an invalid filename in the
install script.  The name was incorrect as the replacment token used for
the filename when updating the install script was incorrect - it was
leaving the existing filename in place while appending the new.
Updated the token replacement to only use the new filename when updating
the install script.
> (gh-388) Update filename token replacement

- automatic/bluej/bluej.nuspec
Validation for the bluej package was failing.  Failures were caused by
invaid licenseUrl and bugTrackerUrl elements - the URLs had been updated
so were no longer availabe for validation against.
Updated the ilcenseUrl and bugTrackerUrl elements to refect the new URLs
at which they are now located.
> (gh-391) Correct buej package validation failures

- automatic/vscode-maven/vscode-maven.nuspec
Package validation was failing due to the DocsUrl element no longer
being resolvable.  This was due to an interim build being published for
which no tag was created.
Currently no clarity on the intended path forward - tags may have been
abandonded or it could just be an error for this build so pinning the
documentation to that for the previous (v0.35.1) published version for
now.
> (gh-393) Reverted documentation URL to v0.35.1

- automatic/mongodb-cli.install/mongodb-cli.install.nuspec
- automatic/mongodb-cli.portable/mongodb-cli.portable.nuspec
- automatic/mongodb-cli/mongodb-cli.nuspec
The base domain for documenation URLs had been updated.  Modifed the
domain prefix on documentation references from docs.mongodb.com to
www.mongodb.com/docs to reflect this.
> (gh-395) Updated domain on documentation URLs

- automatic/kyma-cli/README.md
- automatic/kyma-cli/kyma-cli.nuspec
- automatic/kyma-cli/legal/VERIFICATION.txt
- automatic/kyma-cli/update.ps1
The kyma-cli is outdated on [choco](https://community.chocolatey.org/packages/kyma-cli) (2.0.4 instead of the 2.3.0). AU failed updating the package because the kyma version couldn't be determined:
```powershell
Invalid version:
At C:\Program Files\WindowsPowerShell\Modules\au\2021.7.18\Public\Update-Package.ps1:210 char:46
+ ... ion $Latest.Version)) { throw "Invalid version: $($Latest.Version)" }
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Invalid version: :String) [], RuntimeException
+ FullyQualifiedErrorId : Invalid version:
```
More specifically, the [regex](https://github.com/dgalbraith/chocolatey-packages/blob/master/automatic/kyma-cli/update.ps1#L46) for extracting the kyma version from the package url …
> update kyma-cli to 2.3.0

- automatic/sendtokindle/sendtokindle.nuspec
- automatic/sendtokindle/tools/chocolateyInstall.ps1
Sendtokindle has been updated.  The package needs to be Updated to version 1.1.1.253 to match.
Closes gh-357
Fixes gh-401
> (gh-401) Update sendtokindle version to 1.1.1.253

- automatic/nushell.install/README.md
- automatic/nushell.install/legal/VERIFICATION.txt
- automatic/nushell.install/nushell.install.nuspec
- automatic/nushell.install/tools/chocolateyInstall.ps1
- automatic/nushell.portable/README.md
- automatic/nushell.portable/legal/VERIFICATION.txt
- automatic/nushell.portable/nushell.portable.nuspec
- automatic/nushell.portable/tools/chocolateyInstall.ps1
- automatic/nushell/README.md
- automatic/nushell/nushell.nuspec
- automatic/nushell/update.ps1
The filename patterns for builds of nushell were updated from
nu_0_63_0_windows.msi to nu-0.64.0-x86_64-pc-windows-msvc.msi which broke
automatic package updates.
To address the regular expression used to match versions was updated and the
version match simplified to utilise the regex directly without any
intermediate replacement.
> (gh-404) Update nushell package filename handling

- automatic/gephi/README.md
- automatic/gephi/gephi.nuspec
- automatic/gephi/legal/VERIFICATION.txt
- automatic/gephi/tools/chocolateyInstall.ps1
- automatic/gephi/update.ps1
The automatic updater for the Gephi package was failing since the 0.9.5
update due to a change of the distribution files - x32 and x64 installers
are now produced as build artifacts and the automatic update was failing
as a result.
Modified regular expressions to ensure only a single match and updated
documentation to reflect changes to the package which no longer requires
an external JDK to be available on install.
> (gh-410) Updated to reflect build changes since 0.9.4

- automatic/fluidsynth/README.md
- automatic/fluidsynth/fluidsynth.nuspec
- automatic/fluidsynth/tools/chocolateyInstall.ps1
- automatic/fluidsynth/tools/chocolateyUninstall.ps1
- automatic/fluidsynth/update.ps1
Updates to the Fluidsynth package to:
* ensure the package does not leave residue on updates/removal
* update regular expressions to remove the use of secondary pattern group substitutions
* unzip package files into a consistent location denoted by Get-ToolsLocation
> (gh-399) Fluidsynth package update

- automatic/fluidsynth/tools/chocolateyUninstall.ps1
The package was failing validation due to the use of a private
environment variable.  Updated the uninstall script to remove the use
of $env:chocoateyPackageFolder to address this.
Rather than using the environment variable just resolved the parent
directory of the directory containing the calling script.
> (gh-399) Remove private environment variable

- automatic/vscode-maven/update.ps1
- automatic/vscode-maven/vscode-maven.nuspec
Package validation was failing due to an invalid documentation URL - the versioning scheme for the distribtion had been updated so that it was no longer synchronized with the tagging mechanism on the Github repository.
Updated to use a standard documetnation URL that was persistent across versions and no longer associated with the Github tagged versions and refreshed the regular expression usage.
> (gh-411) Update package documentation reference

- automatic/nheko-reborn/tools/chocolateyUninstall.ps1
Package upgrades were failing due to the presence of the install directory/contents which cause the new install to fail.  The directory is present as the Chocoatey auto-uninstaller is not correctly uninstalling the package - the Qt installer does not appear to be handled correctly by Chocolatey.
To address this automatic uninstall is being skipped and a specific uninstall script which correctly handles the uninstall introduced.
> (gh-363) Correct package upgrade failures

- automatic/neck-diagrams/neck-diagrams.nuspec
- automatic/neck-diagrams/tools/chocolateyinstall.ps1
- automatic/neck-diagrams/update.ps1
The automated build of the neck-diagrams package was failing as the web page structure had changed.  Updated the package to cater for the new format and aligned the package with current approach to packages.
> (gh-384) Correct automated package build

- .appveyor.yml
Update the build image used for Appveyor builds to the Visual Studio 2022 version.
> (gh-427) Update build image

- automatic/remote-desktop-client/update.ps1
The package was not updating correctly due to errors introduced with the x86 installer update.  Corrected these so that the correct URL was used for remote retrieval and replacements.  The 32-bit URLs were also updated to ensure that they only matched against the 32-bit markers.
> (gh-423) Corrected package update

- automatic/nheko-reborn/README.md
- automatic/nheko-reborn/legal/VERIFICATION.txt
- automatic/nheko-reborn/nheko-reborn.nuspec
- automatic/nheko-reborn/tools/chocolateyInstall.ps1
- automatic/nheko-reborn/update.ps1
New package build pushed to address [CVE-2022-39264](https://nvd.nist.gov/vuln/detail/CVE-2022-39264).
> (gh-432) Address CVE-2022-39264

- automatic/angband/update.ps1
- automatic/calibre-dedrm/legal/VERIFICATION.txt
- automatic/calibre-dedrm/update.ps1
- automatic/cloc/update.ps1
- automatic/dbgate/update.ps1
- automatic/fluidsynth/update.ps1
- automatic/foca/update.ps1
- automatic/gephi/update.ps1
- automatic/jruby/update.ps1
- automatic/keys/legal/VERIFICATION.txt
- automatic/keys/update.ps1
- automatic/koodo-reader/README.md
- automatic/koodo-reader/koodo-reader.nuspec
- automatic/koodo-reader/legal/VERIFICATION.txt
- automatic/koodo-reader/tools/chocolateyInstall.ps1
- automatic/koodo-reader/tools/chocolateyUninstall.ps1
- automatic/koodo-reader/update.ps1
- automatic/kui/update.ps1
- automatic/kyma-cli/update.ps1
- automatic/mongodb-cli/update.ps1
- automatic/mongodb-shell/update.ps1
- automatic/naps2/update.ps1
- automatic/nushell/update.ps1
- automatic/pictus/update.ps1
All GitHub packages were broken due to a structural change on the presentation of assets associated with a tag.  With the change to the tag the AU update scripts were no longer capable of determining the version.
Modified the handling to successfully retrieve asset versions from GitHub to repair automated version checks/package updates.
> (gh-431) Modified package updates to handle GitHub structure

- automatic/mongodb-shell/README.md
- automatic/mongodb-shell/mongodb-shell.nuspec
- automatic/mongodb-shell/update.ps1
The mongodb shell main branch had been changed from master to main and the documentation URL had changed.
Aligned with the new GitHub branch structure and corrected the documentation URL.
> (gh-381) Package updates to reflect new URLs

- automatic/sliksvn/README.md
- automatic/sliksvn/legal/VERIFICATION.txt
- automatic/sliksvn/sliksvn.nuspec
- automatic/sliksvn/tools/chocolateyBeforeModify.ps1
- automatic/sliksvn/tools/chocolateyInstall.ps1
- automatic/sliksvn/update.ps1
The sliksvn package was no longer updating due to a change in the resource format - the package binary distribution had changed from raw msi files to msi files additionally packaged in zip files.
Modified the updater to successfully retrieve and handle the msi files packaged in zip files and enhanced the package to utilise shims to provide a default option of not adding the install\bin directory to the path.
> (gh-441) Correct sliksvn package updates

- automatic/openvpn/legal/VERIFICATION.txt
- automatic/openvpn/openvpn.nuspec
- automatic/openvpn/tools/chocolateyInstall.ps1
- automatic/openvpn/update.ps1
The OpenVPN package utilises a versioning scheme which reflects a tag version formatted as x.y.z (major.minor.patch) followed by an additional version increment in the form Ixxx (eg. I004) where xxx represents a version increment based on updates to non-code inclusions/additional binaries.
Updated the automated package script to reflect the use of incremental versioning and update accordingly.  In addition to handling version increments additional changes were:
* updated to version 2.6.0.004
* update bug tracker URL to the new tracker on GitHub
* corrected URL regexes to ensure that they were case sensitive and did not match inappropriately when updating VERIFICATION.txt
* corrected the download URLs in VERIFICATION.txt
> (gh-452) Introduced incremental version handling

- automatic/watchman/update.ps1
Updated watchman package build to address breaks.  Package build was no longer updating due to structural changes with the page structure for GitHub release artifacts.
Package build script updated to use utility methods to correctly extract release artifacts from GitHub pages.
> (gh-451) Update watchman automated package build

- automatic/authme.install/legal/VERIFICATION.txt
- automatic/authme.install/tools/chocolateyInstall.ps1
- automatic/authme.install/update.ps1
- automatic/authme.portable/legal/VERIFICATION.txt
- automatic/authme.portable/tools/chocolateyInstall.ps1
- automatic/authme.portable/tools/chocolateyUninstall.ps1
- automatic/authme/update.ps1
Update authme file handling to reflect the new filename structure used for release artifacts with the 4.0 updates and moved to common utility methods to locate release artifacts on GitHub.
> (gh-459) Update authme file handling

- automatic/authme.install/authme.install.nuspec
- automatic/authme.portable/authme.portable.nuspec
- automatic/authme/authme.nuspec
Package validation was failing due to the docsUrl element.  The location for the package documentation previously referred to no longer exists.
Updated the docsUrl element to refer to  the README.md file in the  GitHub repository.
> (gh-459) Update documentation URL

- automatic/sendtokindle/tools/chocolateyInstall.ps1
- automatic/sendtokindle/update.ps1
Package was previously not updating automatically.
Added support for automated updates leveraging the ETag handling helper function to determine when the binary has been updated/a new version may be available.
> (gh-453) Add automatic update handling

- automatic/sendtokindle/update.ps1
Package update was failing due to missing utility function.
Updated to import the helper scripts and make the ETag handling helper available in the update script.
> (gh-453) Import helper scripts

- automatic/sendtokindle/update.ps1
Package update was failing due to missing Chocolatey install scripts.
Updated to import the Chocolatey install scripts and make the Get-WebFile function available in the update script.
> (gh-453) Import install scripts

- automatic/dotcover-cli/README.md
- automatic/dotcover-cli/dotcover-cli.nuspec
- automatic/dotcover-cli/legal/VERIFICATION.txt
- automatic/dotcover-cli/tools/chocolateyInstall.ps1
- automatic/dotcover-cli/update.ps1
Package build was failing as the URL syntax was invalid - no URL was being retrieved from the JSON describing the dotCover-cli binaries.
The package and JSON were updated to include an additional package type on windows - what was  previously known as windows has been split and now there are windows32 and windows64 versions representing the x86 and x64 architectures respectively. Previously only the x64 architecture was provided and represented as windows.
Modified package update to handle this,  consolidated the regular expressions and added support for the new 32-bit binaries.
> (gh-473) Amended new package detection to handle x86 and x64 architectures

- automatic/openvpn/README.md
- automatic/openvpn/openvpn.nuspec
- automatic/openvpn/tools/chocolateyInstall.ps1
This should resolve #465 
I wonder if it's time to not install any of the other drivers by default?  I really have no idea on their status.
> (gh-465) Install DCO driver by default

- manual/winaero-tweaker.install/README.md
- manual/winaero-tweaker.install/tools/chocolateyinstall.ps1
- manual/winaero-tweaker.install/winaero-tweaker.install.nuspec
- manual/winaero-tweaker.portable/README.md
- manual/winaero-tweaker.portable/tools/chocolateyinstall.ps1
- manual/winaero-tweaker.portable/winaero-tweaker.portable.nuspec
- manual/winaero-tweaker/README.md
- manual/winaero-tweaker/winaero-tweaker.nuspec
Updated Winaero Tweaker package version to 1.55.0.0.
Standard package update to reflect the new version but the archive handling needed to be amended to reflect the inclusion of the patch version in the archive name.
> (gh-484) Updated Winaero Tweaker Package Version 1.55

- automatic/nushell/update.ps1
The regex matching the packages for windows was no longer working as an additional set of packages for aarch64 arm had been introduced.  With the additional packages 2 sets of files were being matched (x86_64 and aarch64).
Updated the regex matching to ensure that only x86_64 packages were matched.
> (gh-486) Updated installer regex for  windows only

- automatic/vscode-python/update.ps1
Modify regex in automatic update script to successfully match against versions with an -insider suffix.
Updates were failing as the addition of the -insider suffix to the required version caused regex matching to break.  The regex was amended to address this.
> (gh-492) Modify regex in automatic update script

- manual/mssqlserver-compact4.0/README.md
The version reference in README.md was against an incorrect package.  Updated the package from go-fonts to the correct mssqlserver-compact4.0.
> (gh-494) Updated version reference in README.md

- automatic/iasl/README.md
- automatic/iasl/iasl.nuspec
- automatic/iasl/legal/LICENSE.txt
- automatic/iasl/legal/VERIFICATION.txt
- automatic/iasl/tools/chocolateyinstall.ps1
- automatic/iasl/update.ps1
The iasl pages were migrated from acpica.org to direct hosting on the Intel site.  This migration broke the existing package updates.
To address this the documentation and package download URLs were updated to refect the new location direct with Intel.
> (gh-498) Updated to reflect iasl migration

- automatic/naps2.install/README.md
- automatic/naps2.install/legal/LICENSE.txt
- automatic/naps2.install/legal/VERIFICATION.txt
- automatic/naps2.install/naps2.install.nuspec
- automatic/naps2.install/tools/ChocolateyInstall.ps1
- automatic/naps2.install/update.ps1
- automatic/naps2.portable/README.md
- automatic/naps2.portable/legal/LICENSE.txt
- automatic/naps2.portable/legal/VERIFICATION.txt
- automatic/naps2.portable/naps2.portable.nuspec
- automatic/naps2.portable/tools/chocolateyInstall.ps1
- automatic/naps2.portable/update.ps1
- automatic/naps2/README.md
- automatic/naps2/naps2.nuspec
- automatic/naps2/update.ps1
Source package artifacts had been updated to have new names in the 7.1 series with the introduction of discrete 32 and 64-bit installers and the modification of the archive names to include -win.
Modified the automatic updater to reflect the new artifacts and naming.
> (gh-501) Modify update to reflect new artifacts

- automatic/sqlean-shell/README.md
- automatic/sqlean-shell/sqlean-shell.nuspec
MathJax had been used to document the package but the MathJax was not being rendered.
Removed the MathJax to address this.
> (gh-503) Remove MathJax from documentation

- automatic/sqlite-shell-x64/README.md
- automatic/sqlite-shell-x64/sqlite-shell-x64.nuspec
Package documentation was incorrect with references to another package and extraneous text had been included.
Updated all package references and removed the extraneous text.
> (gh-505) Correct package documentation

- automatic/nushell/update.ps1
The package build was failing as new release artifacts had been introduced.
Updated the regex matching on the package build to ensure that the full release files `*-msvc-full.msi` were excluded and only the default `*msvc.msi` files were matched.
> (gh-513) Exclude full release files

- automatic/sqlite.analyzer/README.md
- automatic/sqlite.analyzer/sqlite.analyzer.nuspec
- automatic/sqlite.analyzer/update.ps1
- automatic/sqlite.shell/README.md
- automatic/sqlite.shell/sqlite.shell.nuspec
- automatic/sqlite.shell/update.ps1
The tools package for sqlite has been updated to be provided as a 64-bit binary with the 3.43.0 release.  The sqlite tools package build were breaking due to this.
Modified the update and install scripts to be able to correctly retrieve and use the 64-bit versions as opposed to the 32-bit ones.  Also modified the documentation to reflect the 64-bit nature of the binaries and provide instructions on retrieving and pinning the last 32-bit versions 3.43.2.
> (gh-510) Handle 64-bit tool package

- manual/office365proplus/Office365ProPlus.nuspec
- manual/office365proplus/README.md
- manual/office365proplus/tools/chocolateyInstall.ps1
* Updated the Office Deployment Tool for Office 365 Pro to v2403 build 17531.20046.
* Updated documentation to reflect that Windows 2010 or later is reuqired.
> (GH-528) Update the Office Deployment Tool to v2403 build 17531.20046

- automatic/vscode-intellicode/vscode-intellicode.nuspec
The package was valing validation due to the documentation URL no longer being valid.  Updated the URL to reflect the current documentation location.
> (gh-530) Update Documentation Links

- .appveyor.yml
Appveyor Windows build images are pre-installed with Chocolatey 1.4.0.  This was causing issues due to the change in semantic versioning introduced in 2.0 - versions were not being correctly constructed.
Added build configuration to upgrade Chocolatey to latest version in the initial build setup.
> (gh-534) Upgrade Chocolatey in build images

- automatic/openvpn/tools/chocolateyInstall.ps1
The OpenVPN readme file claims that OpenSSL is installed in case no installation parameters are provided. However, I noticed that this is not the case according to the Chocolatey installation script. This pull request adds the `OpenSSL` parameter which includes OpenSSL during the installation to ensure the installation script is in line with documentation.
https://github.com/dgalbraith/chocolatey-packages/blob/3f5827f0655055c8f460fbaaab375db3c98b868a/automatic/openvpn/README.md?plain=1#L53-L55
https://github.com/dgalbraith/chocolatey-packages/blob/3f5827f0655055c8f460fbaaab375db3c98b868a/automatic/openvpn/tools/chocolateyInstall.ps1#L81-L84
> Add OpenSSL as default installation option to be aligned with documentation

- automatic/angband/tools/chocolateyBeforeModify.ps1
- automatic/angband/tools/chocolateyInstall.ps1
- automatic/angband/tools/chocolateyUninstall.ps1
- automatic/angband/update.ps1
The package was not building due to Github changes on asset pages.  Updated to use the common Git library functions to locate assets and corrected issues with the install/update:
* Error shown on package install post shim creation
* Package not cleaning up correctly on uninstall/upgrade
* Error shown on package uninstall
> (gh-537) Update source location handling

- automatic/prime95/legal/VERIFICATION.txt
- automatic/prime95/update.ps1
Filename format was no longer matching the regular expressions due to updates in the format - the number of digits had increased from 3 to 4.  Modified the regular expressions to accommodate and made additional updates to bring the updater into line with current standards.
> (gh-543) Modify regular expressions to match expected filename

- automatic/prime95/update.ps1
The version matching was against an old variable which was not populated.  Updated the variable being matched to ensure that the page content was populated.
> (gh-543) Fix version extraction

- automatic/vscode-maven/legal/VERIFICATION.txt
- automatic/vscode-maven/tools/chocolateyinstall.ps1
- automatic/vscode-maven/update.ps1
The package was not updating as the filename for the vsix extension was not being matched by the regular expressions.  This was due to the base name (sans .vsix extension) being used in the update rather than the full filename - on subsequent runs the regular expression no longer matched on the filename.  Corrected the update to replace with the full filename.
> (gh-546) Correct filename handling

- automatic/vscode-pull-request-github/README.md
- automatic/vscode-pull-request-github/update.ps1
- automatic/vscode-pull-request-github/vscode-pull-request-github.nuspec
Package was no longer updating due to a version update including `-insiders` that impacted the regular expression matching.  Manually reverted to standard versions to correct his and modified regular expression usage to bring the package into line with current standards.
> (gh-549) Correct package updates

- automatic/sqlite.analyzer/update.ps1
- automatic/sqlite.shell/update.ps1
Corrected the logic around extracting the executables from the archive.  The folder was being fully deleted which rendered the package unusable and invalid.  Updated to ensure that the expected files were left in the tools directory on package build.
> (gh-552) Corrected archive extraction logic

- automatic/coreinfo/README.md
- automatic/coreinfo/coreinfo.nuspec
- automatic/coreinfo/tools/chocolateyInstall.ps1
- automatic/coreinfo/update.ps1
The update script was no longer successfully detecting the available software version.  Modified the updater script to correct this and modified regular expression usage to be inline with current repository standards.
> (gh-555) Corrected coreinfo package update script

- automatic/ant/README.md
- automatic/ant/ant.nuspec
- automatic/ant/legal/VERIFICATION.txt
- automatic/ant/update.ps1
Package was no longer updating as the order of files on the download page had been updated.  Corrected this and updated documentation links and regex handling.
> (gh-590) Handle correct file order on download page

- automatic/bluej/README.md
- automatic/bluej/bluej.nuspec
- automatic/bluej/update.ps1
Package was no longer updating following migration to Github. Updated to ensure correct handling and updated documentation links and regex handling.
> (gh-592) Modify updater to retrieve from Github

- automatic/bluej/tools/chocolateyInstall.ps1
- automatic/bluej/update.ps1
The regex matching on the url and checksum was incorrect.    The
leading single quote was not included in the non-matching regular
expression  so the package args were being impacted on replacement.
Corrected the regex handling and updated to match the expected values
for the package version.
> (gh-592) Corrected regex matching for url and checksum

- automatic/dbgate.install/README.md
- automatic/dbgate.install/update.ps1
- automatic/dbgate.portable/README.md
- automatic/dbgate.portable/update.ps1
- automatic/dbgate/README.md
- automatic/dbgate/update.ps1
Package updates were not functioning due to the Github API changes. Modified the updater to use the common functions to address this, and corrected references in README.md to link to the dbgate package rather than mongodb.
> (gh-595) Modified updater to utilise Github common functions

- automatic/naps2/update.ps1
The update script was not functioning in the build environment due to the absence of the appropriate module.  Updated to import the module containing the helper functions.
> (gh-598) Added module import for common helper functions

- automatic/dotcover-cli/README.md
- automatic/dotcover-cli/legal/VERIFICATION.txt
- automatic/dotcover-cli/tools/chocolateyInstall.ps1
- automatic/dotcover-cli/update.ps1
Automatic updates for  the package were failing due to a change in the distribution structure - rather than platform-specifc packages the package, as of version 2005.1, is not ditributed as a universal archive.
Modified the documentation along with the package updater and installation to reflect this.
> (gh-602) Added support for universal archive

- automatic/vscode-spring-boot/README.md
- automatic/vscode-spring-boot/legal/VERIFICATION.txt
- automatic/vscode-spring-boot/tools/chocolateyinstall.ps1
- automatic/vscode-spring-boot/tools/chocolateyuninstall.ps1
- automatic/vscode-spring-boot/update.ps1
- automatic/vscode-spring-boot/vscode-spring-boot.nuspec
The publisher for the package had changed from Pivotal to VMWare so the package was no longer updating.  Modified the package publisher and docuemtnation to reflect the new publisher.
> (gh-606) Updated package publisher details

- automatic/mongodb-cli.install/README.md
- automatic/mongodb-cli.install/legal/VERIFICATION.txt
- automatic/mongodb-cli.install/mongodb-cli.install.nuspec
- automatic/mongodb-cli.portable/README.md
- automatic/mongodb-cli.portable/legal/VERIFICATION.txt
- automatic/mongodb-cli.portable/mongodb-cli.portable.nuspec
- automatic/mongodb-cli/README.md
- automatic/mongodb-cli/mongodb-cli.nuspec
- automatic/mongodb-cli/update.ps1
Software was split from the old repository shared with Atlas CLI to a dedicated stand-alone repository.
Adjusted package documentation, links and updates  to reflect the new repository.
> (gh-585) Updated package to reflect migration new repository

- automatic/dotcover-cli/dotcover-cli.nuspec
The distributed binaries in the package are now contained in a universal archive.  Updated the package documentation to reflect this.
> (gh-613) Updated  documentation to note universal archive distribution

- automatic/dotcover-cli/dotcover-cli.nuspec
The documentation was using generatinv rather than generating.  Updated to correct spelling.
> (gh-613) Corrected spelling in documentation

- automatic/imagej/README.md
- automatic/imagej/imagej.nuspec
- automatic/imagej/legal/VERIFICATION.txt
- automatic/imagej/update.ps1
Updated the package distribution site from https://imagej.nih.gov/ij to https://imagej.net/ij.
> (gh-607) Updated packager distribution site
